config/routes.rb
Moodboards::Application.routes.draw do

  resources :sites

  resources :boards do
    resources :sites
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  attr_accessible :name

  has_many :sites

  validates :name,  :presence => true

end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :url
  attr_accessible :screenshot
  
  validates :url,  :presence => true
  
  belongs_to :board

  has_attached_file :screenshot, :styles => { :medium => "300x300>", :thumb => "100x100>" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render json: @board, status: :created, location: @board }
      else
        format.html { render action: "new" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @sites = Site.all
  
    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @sites }
    end
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boards.each do |board| %>
  <tr>
    <td><%= board.name %></td>
    <td><%= link_to 'Show', board %></td>
    <td><%= link_to 'Edit', edit_board_path(board) %></td>
    <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @board.name %>
</p>


<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/home/index.html.erb
<div id="content">

<ul id="sites">
  <% @sites.each do |site| %>	 
  		<li>
          <%= link_to (site) do 
  	    	  image_tag site.screenshot.url(:medium)
          end %>
          <!-- <%= site.url %><br/> -->
  		</li>
  <% end %>
</ul>

</div>

<!-- 
<% @sites.each do |site| %>
  <tr>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br /> -->

<%= link_to 'New Site', new_site_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moodboards</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
	<a href="/"><h1>moodboards</h1></a>

	<%= link_to '+', new_site_path, :class=>"new-site" %>
	<select id="boards">
		<option>fashion</option>
		<option>startups</option>
		<option>blog</option>
		<option>sports</option>
	</select> 

	</nav>

<div id="content">
	<%= yield %>
</div>

</body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= form_for @site, :url => site_path, :html => { :multipart => true } do |f| %>

	<%= f.label :url %><br />
	<%= f.text_field :url, :class=>"form_text_field" %><br />
<br /><br />
<%= image_tag @site.screenshot.url %><br />
<%= image_tag @site.screenshot.url(:medium) %><br />
<%= image_tag @site.screenshot.url(:thumb) %><br />
<br /><br />
	<%= f.file_field :screenshot %><br /><br />
    <%= f.submit 'Update', :class=>"form_button" %>
<% end %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Url</th>
    <th>screenie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.url %></td>
    <td><%= image_tag site.screenshot.url(:medium) %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>


<%= form_for @site, :url => { :action => "create" }, :html => { :multipart => true } do |f| %>

	<%= f.label :url %><br />
	<%= f.text_field :url, :class=>"form_text_field" %><br />

	<%= f.file_field :screenshot %><br /><br />
    <%= f.submit 'Create', :class=>"form_button" %>
<% end %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @site.url %><br/>
<%= image_tag @site.screenshot.url(:medium) %><br />

</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', "/" %>